# Generated by Django 3.2.9 on 2021-11-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('admission_time', models.TimeField()),
                ('admission_isThisAEmergencyPlannedHospitalization', models.CharField(choices=[('choice1', 'Emergency'), ('choice2', 'Planned')], max_length=255)),
                ('admission_expectedNoOfDays', models.IntegerField()),
                ('admission_daysInICU', models.IntegerField()),
                ('admission_roomType', models.CharField(choices=[('ICU', 'ICU'), ('NICU', 'NICU'), ('High Dependency Unit', 'High Dependency Unit'), ('CCU - Cardiac Care Unit', 'CCU - Cardiac Care Unit'), ('Private ICU', 'Private ICU'), ('Private CCU', 'Private CCU')], default='ICU', max_length=255)),
                ('admission_perDayRoomRent', models.IntegerField()),
                ('admission_expectedCostForInvestigation', models.IntegerField()),
                ('admission_icuCharge', models.IntegerField()),
                ('admission_otCharge', models.IntegerField()),
                ('admission_professionalFeesSurgeon', models.IntegerField()),
                ('admission_madicineConsumablesCostOfImplats', models.IntegerField()),
                ('admission_otherHospitalIfAny', models.CharField(max_length=255)),
                ('admission_allIncludePackageCharge', models.IntegerField()),
                ('admission_sumTotalExpected', models.IntegerField()),
                ('admission_mandatoryPastHistoryMonth', models.CharField(max_length=255)),
                ('admission_mandatoryPastHistoryYear', models.CharField(max_length=255)),
                ('admission_heartDiseaseMonth', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_heartDiseaseYear', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_hypertensionMonth', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_hypertensionYear', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_HyperlipidemiasMonth', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_HyperlipidemiasYear', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_osteoarthritisMonth', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_osteoarthritisYear', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_asthmaOrCOPDOrBronchitisMonth', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_asthmaOrCOPDOrBronchitisYear', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_cancerMonth', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_cancerYear', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_alcoholOrDrugAbuseMonth', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_alcoholOrDrugAbuseYear', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_anyHIVOrSTDOrRelatedAlimentsMonth', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_anyHIVOrSTDOrRelatedAlimentsYear', models.IntegerField(choices=[('Month', 'Month'), ('Year', 'Year')])),
                ('admission_anyOtherAliments', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorandDiagnosisDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_email', models.CharField(max_length=255)),
                ('Contact_number', models.IntegerField()),
                ('doctor_natureOfLiness', models.CharField(max_length=255)),
                ('doctor_releventClinicFindings', models.CharField(max_length=255)),
                ('doctor_durationOfPresentAliment', models.DateTimeField()),
                ('doctor_dateOfFirstConsultation', models.DateField()),
                ('doctor_PastHistoryOfPresentAlignment', models.CharField(max_length=255)),
                ('doctor_provisionalDiagnosis', models.CharField(max_length=255)),
                ('doctor_icdCode', models.CharField(max_length=20)),
                ('doctor_proposedLineOfTreatment', models.CharField(choices=[('Medical Managment', 'Medical Managment'), ('Surgical Managment', 'Surgical Managment'), ('Intensive Care', 'Intensive Care'), ('Investigation', 'Investigation'), ('Non Allopathic Treatment', 'Non Allopathic Treatment')], max_length=255)),
                ('If_Investigation_Or_Medical_Management_Provide_Details', models.CharField(max_length=255)),
                ('Route_Of_Drug_Administration', models.CharField(max_length=255)),
                ('If_Surgical_Name_of_Surgery', models.CharField(max_length=255)),
                ('ICD_Code_10_PCS', models.CharField(max_length=10)),
                ('doctor_ifOtherTratmentProvideDetails', models.CharField(max_length=255)),
                ('doctor_howDidInjuryOccure', models.CharField(max_length=255)),
                ('doctor_inCaseOfAccident', models.BooleanField()),
                ('doctor_reportedToPolice', models.BooleanField()),
                ('doctor_injuryorDiseaseCausedDueToSubstance', models.BooleanField()),
                ('doctor_testAlcohol', models.BooleanField()),
                ('doctor_inCaseMaternity', models.CharField(choices=[('1', 'G'), ('2', 'P'), ('3', 'L'), ('4', 'A')], max_length=255)),
                ('doctor_expectedDateOfDelivery', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_details_name', models.CharField(max_length=255)),
                ('patient_details_gender', models.CharField(max_length=255)),
                ('patient_details_ageYear', models.CharField(max_length=20)),
                ('patient_details_ageMonth', models.CharField(max_length=20)),
                ('patient_details_date', models.DateField()),
                ('patient_details_contact_number', models.CharField(max_length=10)),
                ('patient_details_numberOfAttendingRelative', models.CharField(max_length=10)),
                ('patient_details_insuredMemberIdCardNo', models.CharField(max_length=255)),
                ('patient_details_policyNumberorCorporateName', models.CharField(max_length=255)),
                ('patient_details_EmployeeId', models.CharField(max_length=255)),
                ('patient_details_HealthInsurance', models.CharField(max_length=255)),
                ('patient_details_familyPhysician', models.CharField(max_length=255)),
                ('patient_details_currentAddress', models.CharField(max_length=500)),
                ('patient_details_currentCity', models.CharField(max_length=255)),
                ('patient_details_occupation', models.CharField(max_length=255)),
            ],
        ),
    ]
